; PlatformIO Project Configuration File
; ESP32-WROOM-32D + INMP441 I2S Digital MEMS Microphone

[platformio]
default_envs = esp32dev
description = Modular ESP32 I2S audio acquisition firmware for INMP441 MEMS microphone

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Library Dependency Finder Settings
lib_ldf_mode = deep+
lib_deps = 
    edge-impulse-sdk


; Serial Monitor Settings
monitor_speed = 115200
monitor_filters = 
    esp32_exception_decoder
    default
    time

; Upload Settings
upload_speed = 921600

; Build Options
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -O3
    -Wno-unused-variable
    -Wno-unused-but-set-variable
    -Ilib/edge-impulse-sdk
    -Ilib/edge-impulse-sdk/model-parameters
    -Ilib/edge-impulse-sdk/edge-impulse-sdk
    -Ilib/edge-impulse-sdk/tflite-model
    -Ilib/edge-impulse-sdk/edge-impulse-sdk/third_party/flatbuffers/include
    -Ilib/edge-impulse-sdk/edge-impulse-sdk/third_party/gemmlowp
    -Ilib/edge-impulse-sdk/edge-impulse-sdk/third_party/ruy
    -Ilib/edge-impulse-sdk/edge-impulse-sdk/porting/espressif/ESP-NN/include


